name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
  REF: ${{ (github.event_name == 'pull_request' && github.base_ref) || github.ref_name }}
on:
  - pull_request_target
  - push

jobs:
  Checkstyle-Lint-Build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'DevDogs-UGA/Community-Resource-Forum' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ariga/setup-atlas@master
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Validate Formatting and Linting
        run: SKIP_ENV_VALIDATION=true pnpm turbo lint prettier typecheck
      - name: Dry Run Project Deployment (for PRs)
        if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          SKIP_ENV_VALIDATION=true pnpm turbo build
          SKIP_ENV_VALIDATION=true pnpm dlx vercel env pull ${{ env.ENV_CONFIG }} --token=${{ secrets.VERCEL_TOKEN }} .env
          SKIP_ENV_VALIDATION=true pnpm dlx dotenv-cli -- sh -c 'atlas schema apply --config file://volumes/atlas/atlas.hcl --env remote --dev-url docker://mysql/8/example --url mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DATABASE --dry-run'
        env:
          ENV_CONFIG: ${{ (env.REF == 'main' && '--environment=production') || format('--environment=preview --git-branch={0}', env.REF) }}
      - name: Deploy Project (for Pushes)
        if: ${{ github.event_name == 'push' }}
        run: |
          pnpm dlx vercel env pull ${{ env.ENV_CONFIG }} --token=${{ secrets.VERCEL_TOKEN }} .env
          SKIP_ENV_VALIDATION=true pnpm db:generate
          SKIP_ENV_VALIDATION=true pnpm dlx dotenv-cli -- sh -c 'atlas schema apply --config file://volumes/atlas/atlas.hcl --env remote --dev-url docker://mysql/8/example --url mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DATABASE --auto-approve'
          SKIP_ENV_VALIDATION=true pnpm dlx dotenv-cli -- pnpm dlx tsx addTagsToDatabase.ts
          SKIP_ENV_VALIDATION=true pnpm dlx vercel deploy ${{ env.BUILD_CONFIG }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          ENV_CONFIG: ${{ (env.REF == 'main' && '--environment=production') || format('--environment=preview --git-branch={0}', env.REF) }}
          BUILD_CONFIG: ${{ (env.REF == 'main' && '--prod') || ' ' }}
